
class CustomerProfilesPage(object):
    CP_link = 'a[id="appselect:_idJsp22"]'

    PanelToggle = 'h3[class="csPanelToggle"]'
    General = 'input[id="custinfosearch:listToSearch"]'
    QDUT = 'input[id="custinfosearch:listToSearch_1"]'
    CPI = 'input[id="custinfosearch:listToSearch_2"]'
    Insurance = 'input[id="custinfosearch:listToSearch_3"]'
    Leads = 'input[id="custinfosearch:listToSearch_4"]'
    SPI = 'input[id="custinfosearch:listToSearch_5"]'

    Custinfo_id1 = 'input[id="custinfosearch:_idJsp29"]'
    Custinfo_id2 = 'input[id="custinfosearch:_idJsp32"]'
    Custinfo_name = 'input[id="custinfosearch:_idJsp35"]'
    Custinfo_Archives = 'select[id="custinfosearch:_idJsp37"]'
    Custinfo_Archives_input = 'input[id="custinfosearch:_idJsp62"]'
    TRB = 'select[id="custinfosearch:_idJsp65"]'
    AUD = 'select[id="custinfosearch:_idJsp69"]'
    TRB_Input1 = 'input[id="custinfosearch:_idJsp83"]'
    TRB_Input2 = 'input[id="custinfosearch:_idJsp86"]'
    TMD_to_time1 = 'select[id="custinfosearch:_idJsp90"]'
    TMD_to_time2 = 'input[id="custinfosearch:_idJsp103"]'
    TMD_to_time3 = 'input[id="custinfosearch:_idJsp105"]'
    Custinfo_label1 = 'select[id="custinfosearch:labelClass1"]'
    Custinfo_label2 = 'select[id="custinfosearch:_idJsp111"]'
    Current_hold_category1 = 'input[id="custinfosearch:_idJsp117"]'
    Current_hold_category2 = 'input[id="custinfosearch:_idJsp117_1"]'
    Current_hold_category3 = 'input[id="custinfosearch:_idJsp117_2"]'
    Current_hold_category4 = 'input[id="custinfosearch:_idJsp117_3"]'
    Current_hold_category5 = 'input[id="custinfosearch:_idJsp117_4"]'
    Fund_flow = 'input[id="custinfosearch:_idJsp125"]'

    Sort_list1 = 'select[id="custinfosearch:_idJsp321"]'
    Sort_list2 = 'select[id="custinfosearch:_idJsp327"]'
    Customertype_list = 'select[id="custinfosearch:_idJsp380"]'
    Gender_list = 'select[id="custinfosearch:_idJsp389"]'
    age_list = 'select[id="custinfosearch:_idJsp395"]'
    country_list = 'select[id="custinfosearch:_idJsp406"]'
    birthday_list = 'select[id="custinfosearch:_idJsp421"]'
    career_list = 'select[id="custinfosearch:_idJsp437"]'
    RPQ_list = 'select[id="custinfosearch:_idJsp442"]'
    TRB_list = 'select[id="custinfosearch:_idJsp452"]'
    RM_list = 'select[id="custinfosearch:_idJsp461"]'
    Resident_list = 'select[id="custinfosearch:_idJsp466"]'
    source_list = 'select[id="custinfosearch:_idJsp472"]'

    C_tab1 = 'a[id="custinfosearch:id_tab_1_1"]'
    C_tab2 = 'a[id="custinfosearch:id_tab_1_2"]'
    C_tab3 = 'a[id="custinfosearch:id_tab_1_3"]'
    C_tab4 = 'a[id="custinfosearch:id_tab_1_4"]'
    C_tab5 = 'a[id="custinfosearch:id_tab_1_5"]'
    C_tab6 = 'a[id="custinfosearch:id_tab_1_6"]'

    C_tab1_background = 'textarea[id="custinfosearch:remark_1_1"]'
    C_tab1_childrenplan = 'textarea[name="custinfosearch:_idJsp708"]'
    C_tab1_children_gender1 = 'select[id="custinfosearch:_idJsp712"]'
    C_tab1_children_birth1 = 'input[id="custinfosearch:_idJsp717"]'
    C_tab1_children_gender2 = 'select[id="custinfosearch:_idJsp722"]'
    C_tab1_children_birth2 = 'input[id="custinfosearch:_idJsp727"]'
    C_tab1_children_gender3 = 'select[id="custinfosearch:_idJsp732"]'
    C_tab1_children_birth3 = 'input[id="custinfosearch:_idJsp737"]'
    C_tab1_parentplan = 'textarea[name="custinfosearch:_idJsp742"]'
    C_tab1_pensionplan = 'textarea[name="custinfosearch:_idJsp746"]'
    C_tab1_holding = 'select[id="custinfosearch:_idJsp751"]'
    C_tab1_deman = 'select[id="custinfosearch:_idJsp759"]'
    C_tab1_overseademand = 'textarea[name="custinfosearch:_idJsp766"]'
    C_tab1_other = 'textarea[name="custinfosearch:_idJsp770"]'

    C_tab2_1 = 'textarea[name="custinfosearch:_idJsp775"]'
    C_tab2_2 = 'textarea[name="custinfosearch:_idJsp779"]'
    C_tab2_3 = 'textarea[name="custinfosearch:_idJsp783"]'
    C_tab2_4 = 'textarea[name="custinfosearch:_idJsp787"]'
    C_tab2_5 = 'textarea[name="custinfosearch:_idJsp791"]'

    C_tab3_1 = 'textarea[name="custinfosearch:_idJsp796"]'
    C_tab3_2 = 'textarea[name="custinfosearch:_idJsp800"]'
    C_tab3_3 = 'textarea[name="custinfosearch:_idJsp804"]'
    C_tab3_4 = 'textarea[name="custinfosearch:_idJsp808"]'
    C_tab3_5 = 'textarea[name="custinfosearch:_idJsp812"]'
    C_tab3_6 = 'textarea[name="custinfosearch:_idJsp816"]'

    C_tab4_1 = 'textarea[name="custinfosearch:_idJsp818"]'

    C_tab5_1 = 'input[id=""]'
    C_tab5_2 = 'input[id=""]'
    C_tab5_3 = 'input[id=""]'
    C_tab5_4 = 'input[id=""]'
    C_tab5_5 = 'input[id=""]'
    C_tab5_6 = 'input[id=""]'

    C_tab6_1 = 'select[id="custinfosearch:list161111"]'
    C_tab6_2 = 'select[id="custinfosearch:_idJsp1023"]'
    C_tab6_3 = 'select[id="custinfosearch:_idJsp1027"]'
    C_tab6_4_1 = 'input[id="custinfosearch:_idJsp1035"]'
    C_tab6_4_2 = 'input[id="custinfosearch:_idJsp1035_1"]'
    C_tab6_4_3 = 'input[id="custinfosearch:_idJsp1035_2"]'
    C_tab6_4_4 = 'input[id="custinfosearch:_idJsp1035_3"]'
    C_tab6_4_5 = 'input[id="custinfosearch:_idJsp1035_4"]'
    C_tab6_4_6 = 'input[id="custinfosearch:_idJsp1035_5"]'
    C_tab6_4_7 = 'input[id="custinfosearch:_idJsp1042"]'

    E_tab1 = 'a[id = "custinfosearch:id_tab_2_1"]'
    E_tab2 = 'a[id = "custinfosearch:id_tab_2_2"]'
    E_tab3 = 'a[id = "custinfosearch:id_tab_2_3"]'
    E_tab4 = 'a[id = "custinfosearch:id_tab_2_4"]'
    E_tab5 = 'a[id = "custinfosearch:id_tab_2_5"]'
    E_tab6 = 'a[id = "custinfosearch:id_tab_2_6"]'
    E_tab7 = 'a[id = "custinfosearch:id_tab_2_7"]'
    E_tab8 = 'a[id = "custinfosearch:id_tab_2_8"]'
    E_tab9 = 'a[id = "custinfosearch:id_tab_2_9"]'
    E_tab10 = 'a[id = "custinfosearch:id_tab_2_10"]'
    E_tab11 = 'a[id = "custinfosearch:id_tab_2_11"]'
    E_tab12 = 'a[id = "custinfosearch:id_tab_2_12"]'
    E_tab13 = 'a[id = "custinfosearch:id_tab_2_13"]'
    E_tab14 = 'a[id = "custinfosearch:id_tab_2_14"]'
    E_tab15 = 'a[id = "custinfosearch:id_tab_2_15"]'

    search_button = 'input[id="custinfosearch:_idJsp14"]'
    clear_button = 'a[id="custinfosearch:_idJsp11"]'
    # exit_button = 'a[id = "custinfosearch:_idJsp1907"]'
    exit_button = 'a[id = "custinfosearch:_idJsp1906"]'







